spring:
  application:
    name: order_service

  datasource:
    url: "jdbc:postgresql://localhost:5432/liquorservices?currentSchema=order_service"
    username: "postgres"
    password: "admin"
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        default_schema: "order_service"
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: "update"
    show-sql: "true"
    format-sql: "true"

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,liveness,readiness

server:
  port: 8082

PRODUCT_SERVICE_URL: "http://localhost:8081/api/product"