package com.ecommerce.order_service.model;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Getter
@Setter
@Table(
        name = "t_cart",
        schema = "order_service",
        // Explicitly define the UNIQUE constraint on user_cart_id for JPA schema generation
        uniqueConstraints = @UniqueConstraint(columnNames = {"user_cart_id"})
)
@Data
public class Cart {

    @Id
    @Column(name = "id")
    private UUID id; // This will be the CartId generated by the service

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name = "last_activity_at", nullable = false)
    private LocalDateTime lastActivityAt;

    @Column(name = "expires_at")
    private LocalDateTime expiresAt; // For cleanup strategy

    @Column(name = "guest_cart_id")
    private UUID guest_cart_id;
    @Column(name = "user_cart_id")
    private UUID user_cart_id;

    public Cart(){
        this.createdAt = LocalDateTime.now();
        this.lastActivityAt = LocalDateTime.now();
    }

    public Cart(UUID id, UUID guest_cart_id, LocalDateTime expiresAt) {
        this(); // Call default constructor
        this.id = id;
        this.expiresAt = expiresAt;
        this.guest_cart_id = guest_cart_id;
    }
}
