package com.ecommerce.order_service.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Getter
@Setter
@Table (name = "t_cart_guest", schema = "order_service")
public class GuestCart {

    @Id
    private UUID id; // This will be the guestCartId generated by the service

    @Column(nullable = false)
    private LocalDateTime createdAt;

    @Column(nullable = false)
    private LocalDateTime lastActivityAt;

    @Column
    private LocalDateTime expiresAt; // For cleanup strategy

    public GuestCart(){
        this.createdAt = LocalDateTime.now();
        this.lastActivityAt = LocalDateTime.now();
    }

    public GuestCart(UUID id, LocalDateTime expiresAt) {
        this(); // Call default constructor
        this.id = id;
        this.expiresAt = expiresAt;
    }
}
